### ISSUE TITLE
Find Something to Do

### ISSUE THREAD

**Issue by spencerhyphengold** [jeandanielchung/dc-bog-product-summer-2019#4]
### Make it
- fun
- flashy
- fabulous
- involve food
### Todo
- [ ] brainstorm some fun ideas
- [ ] ask friends for help
- [ ] create a poll asking the group for ideAS
